### ISSUE TITLE
Make available direct link to download

### ISSUE THREAD

**Issue by zzo38** [sgadrat/super-tilt-bro#4]
You should also make the ROM file (UNROM) available as a direct download link (without JavaScripts, and even without HTML so that curl/wget can be used too), as an alternative than needing itch.io.

I played a older version, and this game is good.

It says is available two versions, being RAINBOW mapper and UNROM mapper (since RAINBOW mapper is not commonly implemented).

If you want to use expansion audio, then a VRC6 version might be suitable, since I think it is the same sound as RAINBOW mapper. Some of the other features, such as PRG ROM banking and scanline IRQ, also seem like they would be compatible, too. (VRC6 can also use ROM name tables, but I think some emulators do not implement this feature, and it might not be needed for this program anyways.) (However, possibly some things that I may have missed, too. And so far does not seem to use expansion audio (as far as I can tell, by looking at data files), so I suppose UNROM might be good enough for now, anyways.)

**Comment by sgadrat** [comment]
Hello,

Thanks for reaching up and enjoying the game.

Maintaining builds up to date is non-negligible work that I have to take aside from developing the game itself. To limit its impact, I maintain distribution on only one place (which happens to be itch.io.) To get the ROM without javascript, the only supported way is to clone this repository and build it yourself. Full build instruction should be in the readme, please let me know if something is missing. (Released versions are tagged accordingly, and the master shouldn't be broken too often.)

Sorry to be negative on that, but I have to limit maintenance tasks creep, it is already pretty heavy on release days.

Now for the other topics:

Indeed, RAINBOW is only supported by our forked FCEUX for now. The mapper is still being developped, so it's specs change quite often. The UNROM build, as you noticed is a compatibility build, working on most emulators. You'll notice however that the UNROM build is 512 KB, while the mapper only supports 128 KB, this is a trick used because emulators support it, but there is no real hardware running it (except the everdrive). The build also outputs an UNROM-512 version, which is less supported by emulators but could easily be flashed on compatible carts that are easy to find.

The use of VRC6, at least for the main theme, is in the backlog. As you noticed RAINBOW extra channels are very VRC6-like, this is no coincidence :) When that happens, it will be optional, and UNROM roms will still be available, without the extra channels, with tracks made to be enhanced by VRC6 but still good without.

In Super Tilt Bro., I voluntarily refrain from using scanline IRQs and other fancy mapper features (aside of internet connectivity.) This ensure I'll always be able to produce ROMs for simpler mappers. RAINBOW however is not made only for Super Tilt Bro. and is a super powerful, full-featured mapper. I just happen to deactivate most features on boot and proceed to ignore them after that.

I hope I addressed your curiosity, and again am sorry but have to decline to maintain yet another official download place. If you want to be sure what is the latest released version, the source of truth is itch.io.
